export const columnInfos = {
    projectsColumnInfo: [{
      columnName: "名称",
      sortable: true,
      isURL: false,
      keyword: "projectName",
      isRouter: true,
      isDate: false,
      targetURL: "/project/",
      paramKeyword: "projectId"
    }, {
      columnName: "平台",
      sortable: false,
      isURL: false,
      keyword: "platform",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "所用语言",
      sortable: false,
      isURL: false,
      keyword: "language",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "地址",
      sortable: false,
      isURL: true,
      keyword: "homepageUrl",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "创建时间",
      sortable: true,
      isURL: false,
      keyword: "createT",
      isRouter: false,
      isDate: true,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "更新时间",
      sortable: true,
      isURL: false,
      keyword: "updateT",
      isRouter: false,
      isDate: true,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "版本",
      sortable: true,
      isURL: false,
      keyword: "latestReleaseN",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "仓库地址",
      sortable: false,
      isURL: true,
      keyword: "repositoryUrl",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }
    ],
  
    repositoriesColumnInfo: [{
      columnName: "名称",
      sortable: true,
      isURL: false,
      keyword: "repositoryName",
      isRouter: true,
      isDate: false,
      targetURL: "/repository/",
      paramKeyword: "repositoryId"
    }, {
      columnName: "平台",
      sortable: false,
      isURL: false,
      keyword: "hostType",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "所有者",
      sortable: false,
      isURL: false,
      keyword: "repositoryOwner",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "所用语言",
      sortable: false,
      isURL: false,
      keyword: "language",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "地址",
      sortable: false,
      isURL: true,
      keyword: "homepageUrl",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "创建时间",
      sortable: true,
      isURL: false,
      keyword: "createT",
      isRouter: false,
      isDate: true,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "更新时间",
      sortable: true,
      isURL: false,
      keyword: "updateT",
      isRouter: false,
      isDate: true,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "能否fork",
      sortable: false,
      isURL: false,
      keyword: "canFork",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "fork数量",
      sortable: true,
      isURL: false,
      keyword: "forkCount",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "watcher数量",
      sortable: true,
      isURL: false,
      keyword: "watcherCount",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "star数量",
      sortable: true,
      isURL: false,
      keyword: "starCount",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "贡献者数量",
      sortable: true,
      isURL: false,
      keyword: "contributorCount",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }, {
      columnName: "issue数量",
      sortable: true,
      isURL: false,
      keyword: "openIssueCount",
      isRouter: false,
      isDate: false,
      targetURL: "",
      paramKeyword: ""
    }
    ]
  }
  